name: Example Usage
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: 'ECR repository name'
        required: true
        default: 'my-app'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Get latest ECR image
        id: ecr
        uses: ouchi2501/ecr-image-resolver@v1.0.0
        with:
          repository-name: ${{ github.event.inputs.repository-name }}
          aws-region: 'us-east-1'
      
      - name: Show results
        run: |
          echo "Latest tag: ${{ steps.ecr.outputs.latest-tag }}"
          echo "Latest image URI: ${{ steps.ecr.outputs.latest-image-uri }}"
          echo "Image digest: ${{ steps.ecr.outputs.image-digest }}"